name: fl_geocoder
description: Forward and reverse geocoding using Google Maps Platform Geocoding API.
version: 0.1.0+1
homepage: https://github.com/fernan542/fl_geocoder

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: any
  json_annotation: ^4.4.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.1.0
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
